Comments1
BeastJsWeb/1-st-project-26.01.22 pull request #1
Opened 2022-02-05 12:38 UTC by BeastJsWeb

2022-02-05 17:54 UTC, molotow11 requested changes

2022-02-05 17:54 UTC, molotow11 commented on index.html
> +					<a href="#" class="button--hover">Сообщество</a>
`button--hover` по идее класс тут не нужен, смысоа в нем нет, если ты мог выборку сделать через `.js-block-2__btns a`

2022-02-05 17:54 UTC, molotow11 commented on index.html
> +						</div>
тут что-то с форматом страшно не читаемое

2022-02-05 17:54 UTC, molotow11 commented on index.html.bak
>  					<a class="js-theme" href="#"><img src="images/icon24.png">Тема</a>
зачем тебе файл .bak если у тебя теперь гит есть

2022-02-05 17:54 UTC, molotow11 commented on scripts/script.js
> +        if (btn === areaBtns[1] && textarea.value.toString() !== '' && localStorage.getItem('note') !== null) {
так не делают, нужно отдельно клик на каждую кнопку лучше тут, а не `areaBtns[0]`, `areaBtns[1]` так не понятно вообще что за кнопки то. и делай больше комментариев понятных, вообще хрен поймёшь )

2022-02-05 17:54 UTC, molotow11 commented on scripts/script.js
> +                if (btn === noteTextBtns[1]) {
здесь так же, делай отедбнл клин на кнопки, не выбирают элементы таким образом типа как у тебя `noteTextBtns[1]` ...

2022-02-05 17:54 UTC, molotow11 commented on scripts/script.js
> +            localStorage.setItem('note', textarea.value.toString());
а ты проверял вообще оно сохраняет реально? у меня чё-то после перезагрузки страницы опять пусто там

2022-02-06 03:14 UTC, BeastJsWeb commented on index.html
> +						</div>
странно , у меня норм все

2022-02-06 03:32 UTC, BeastJsWeb commented on scripts/script.js
> +            localStorage.setItem('note', textarea.value.toString());
да, сохраняет) а че то я не подумал вывести после перезагрузки просто :) я шо то подумал что когда сайт подключат оно само не будет пропадать

2022-02-08 10:27 UTC, closed without merging