js код отформатирован утилитой в vs. глянь какого функционала не хватает для завершенного проекта)
BeastJsWeb/1-st-project-26.01.22 pull request #2
Opened 2022-02-07 10:47 UTC by BeastJsWeb

https://beastjsweb.github.io/1-st-project-26.01.22/

2022-02-08 06:08 UTC, molotow11 commented
старый PR мержани сперва и тут конфликты пофиксь

2022-02-08 06:16 UTC, molotow11 requested changes
Хз короче, чё-то дофига как-то кода ) 
Убери лишние файлы .bak и т.д.
И лучше авто форматеры кода не использовать, сам правь.
Заметка не удаляется по клику на крестик кстати

2022-02-08 06:16 UTC, molotow11 commented on scripts/script.js
> +  const noteBtnSave = textareaWrapper.querySelector(".js-textarea__button-1");
Всегда лучше по id такие элементы находить, а у тебя везде классы

2022-02-09 09:46 UTC, BeastJsWeb commented
Заметка не удаляется по клику на крестик кстати

странно, у меня нром все)

2022-02-09 13:53 UTC, molotow11 commented
@BeastJsWeb 
Resolve conflicts делай

2022-02-15 11:28 UTC, closed without merging